# Artificial Neural Network projet stage 
---
 Projet Stage *BEY SOLAR* 



### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import random as python_random

In [ ]:
tf.__version__
np.random.seed(123)
python_random.seed(123)
tf.random.set_seed(123)

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('L_Refreg_advanced.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[100 15 'oui' 20 10]
 [95 10 'non' 17 7]
 [80 11 'oui' 13 6]
 [75 9 'oui' 15 5]
 [59 4 'oui' 19 5]
 [88 12 'non' 17 6]
 [33 3 'oui' 12 4]
 [46 5 'oui' 16 5]
 [45 5 'non' 17 5]
 [102 19 'non' 21 10]
 [83 13 'non' 23 9]
 [71 17 'oui' 18 8]
 [26 4 'non' 15 3]
 [49 5 'non' 14 4]
 [78 8 'non' 19 7]
 [82 9 'non' 18 9]
 [72 11 'non' 17 6]
 [69 7 'oui' 16 5]
 [37 5 'non' 12 4]
 [96 10 'non' 22 9]
 [115 18 'non' 18 10]
 [75 7 'oui' 16 9]
 [33 4 'oui' 15 8]
 [42 6 'oui' 16 9]
 [56 5 'oui' 16 10]
 [133 9 'non' 19 7]
 [15 1 'oui' 10 9]
 [140 10 'oui' 16 8]
 [56 6 'oui' 15 7]
 [46 5 'oui' 16 10]
 [35 2 'oui' 14 8]
 [46 4 'oui' 11 7]
 [49 5 'oui' 13 9]
 [126 15 'non' 22 7]
 [162 16 'non' 15 10]
 [56 3 'oui' 16 8]
 [26 1 'oui' 15 6]
 [46 5 'oui' 19 4]
 [17 2 'oui' 19 9]
 [52 6 'oui' 17 6]
 [16 2 'oui' 15 5]
 [14 2 'oui' 16 4]
 [62 6 'oui' 11 6]
 [44 5 'oui' 13 9]
 [65 6 'oui' 15 10]
 [23 2 'oui' 11 7]
 [46 4 'oui' 12 7]
 [120 18 'non' 22 8]
 [101 9 'oui' 16 9]
 [140 11 'oui' 14 8]
 [56 5 'oui' 16 7]

In [ ]:
print(y)

[1 0 1 0 1 0 1 0 1 1 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1
 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 1 1
 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 1 0 1 1 1 1 0 1 0 1 0 0 1 1
 1 0 1 1 0 0 1 0 1 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 1 1 0 0 1 0 1 0 1 0 1 0 1
 1 1 1 1 0 0 1 1 0 1 0 1 1 0 1 0 1 1 0 1 0 1 0 0 0 1 0 0 1 1 1 0 0 1 1 0 1
 0 1 1 1 0 0 0 0 0 1 0 0 0 1 1]


### Encoding categorical data

Label Encoding the "isolation thermique" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
print(X)

[[100 15 1 20 10]
 [95 10 0 17 7]
 [80 11 1 13 6]
 [75 9 1 15 5]
 [59 4 1 19 5]
 [88 12 0 17 6]
 [33 3 1 12 4]
 [46 5 1 16 5]
 [45 5 0 17 5]
 [102 19 0 21 10]
 [83 13 0 23 9]
 [71 17 1 18 8]
 [26 4 0 15 3]
 [49 5 0 14 4]
 [78 8 0 19 7]
 [82 9 0 18 9]
 [72 11 0 17 6]
 [69 7 1 16 5]
 [37 5 0 12 4]
 [96 10 0 22 9]
 [115 18 0 18 10]
 [75 7 1 16 9]
 [33 4 1 15 8]
 [42 6 1 16 9]
 [56 5 1 16 10]
 [133 9 0 19 7]
 [15 1 1 10 9]
 [140 10 1 16 8]
 [56 6 1 15 7]
 [46 5 1 16 10]
 [35 2 1 14 8]
 [46 4 1 11 7]
 [49 5 1 13 9]
 [126 15 0 22 7]
 [162 16 0 15 10]
 [56 3 1 16 8]
 [26 1 1 15 6]
 [46 5 1 19 4]
 [17 2 1 19 9]
 [52 6 1 17 6]
 [16 2 1 15 5]
 [14 2 1 16 4]
 [62 6 1 11 6]
 [44 5 1 13 9]
 [65 6 1 15 10]
 [23 2 1 11 7]
 [46 4 1 12 7]
 [120 18 0 22 8]
 [101 9 1 16 9]
 [140 11 1 14 8]
 [56 5 1 16 7]
 [49 4 0 14 10]
 [89 8 1 19 4]
 [89 10 0 17 5]
 [19 2 1 16 6]
 [89 5 1 18 9]
 [89 6 1 17 8]
 [48 4 0 18 7]
 [156 16 1 20 4]
 [146 14 1 18 6]
 [198 19 1 19 9]
 [146 12 0 23 8]
 [46 5 1 17 4]
 [59 8 0 16 1

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=18, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'SGD', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 42, epochs = 180)

Epoch 1/180
4/4 [==============================] - 0s 3ms/step - loss: 0.6938 - accuracy: 0.5063
Epoch 2/180
4/4 [==============================] - 0s 2ms/step - loss: 0.6937 - accuracy: 0.5000
Epoch 3/180
4/4 [==============================] - 0s 1ms/step - loss: 0.6937 - accuracy: 0.4938
Epoch 4/180
4/4 [==============================] - 0s 2ms/step - loss: 0.6935 - accuracy: 0.5250
Epoch 5/180
4/4 [==============================] - 0s 2ms/step - loss: 0.6934 - accuracy: 0.5188
Epoch 6/180
4/4 [==============================] - 0s 1ms/step - loss: 0.6933 - accuracy: 0.5188
Epoch 7/180
4/4 [==============================] - 0s 2ms/step - loss: 0.6933 - accuracy: 0.5188
Epoch 8/180
4/4 [==============================] - 0s 2ms/step - loss: 0.6931 - accuracy: 0.5063
Epoch 9/180
4/4 [==============================] - 0s 1ms/step - loss: 0.6931 - accuracy: 0.5125
Epoch 10/180
4/4 [==============================] - 0s 2ms/step - loss: 0.6929 - accuracy: 0.5063
Epoch 11/180
4/4 [===========

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [ ]:
print(ann.predict(sc.transform([[64, 6, 1, 15, 9,]])) > 0.5)

[[ True]]


### Predicting the Test set results 

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 4 10]
 [ 2 24]]


0.7